[package]
name = "test_canister"
version.workspace = true
edition.workspace = true

[dependencies]
candid = { workspace = true }
ic_mple_client = { workspace = true }
ic-cdk = { workspace = true }
serde = { workspace = true }
